### ISSUE TITLE
Unterschiedliche Formatierung bei deutsch-Übersetzung

### ISSUE THREAD

**Issue by hardl1** [sbormann/ioBroker.alias-manager#16]
**Describe the bug**  
Wenn im Browser automatische Übersetzung auf deutsch eingestellt ist, wird bei manchen Werten 0,000 und bei anderen 0.000 formatiert. Bei englisch immer 0.000.
Im Alias-Manager ist bei allen Werten nur "val/1000" eingetragen.
Ich kann nicht nachvollziehen, bei welchen Werten sich das ändert.
Manchmal sind es 0, manchmal 1 oder 2 Werte mit ","

**Versions:**  
 - Adapter version: 1.2.4
 - JS-Controller version: 3.3.15
 - Node version: 12.22.2
 - Operating system: IOS Big-sur
 - 
z.B.: conspac
Verbrauch mit ",":
<img width="1259" alt="Bildschirmfoto 2021-08-31 um 14 15 17" src="https://user-images.githubusercontent.com/38688960/131503120-02ae22cd-cb7d-48c5-b492-3b4a018e84b0.png">

<img width="1280" alt="Bildschirmfoto 2021-08-31 um 14 15 44" src="https://user-images.githubusercontent.com/38688960/131503259-02952983-a741-4ce1-98ef-ff314ab2de41.png">
------------------------------------------------------------------

Verbrauch mit ".":
<img width="1301" alt="Bildschirmfoto 2021-08-31 um 14 28 56" src="https://user-images.githubusercontent.com/38688960/131503288-2ea35790-23bb-4785-9c3e-8d0024932182.png">

<img width="1282" alt="Bildschirmfoto 2021-08-31 um 14 29 37" src="https://user-images.githubusercontent.com/38688960/131503304-d9c570bf-a3a4-4887-9c2a-9d03e6fcbe40.png">

**Comment by sbormann** [comment]
Hi,
ich denke, die Frage gehört zum Admin (Darstellungsproblem?) oder js-controller (Umrechnungsproblem?).
Mit dem Alias-Manager werden die Aliase lediglich angelegt, mit Leben gefüllt werden Sie vom js-controller.
@Apollon77 kannst Du hier helfen?
LG

**Comment by hardl1** [comment]
Ich nutze Google Chrome auf einem macbook. Im Browser habe ich meist "Englisch immer auf deutsch übersetzen" eingestellt.

<img width="1136" alt="Bildschirmfoto 2021-09-04 um 10 40 27" src="https://user-images.githubusercontent.com/38688960/132088585-d1f2cc3b-fe3e-4777-96fa-5a1ce5de2095.png">

ioBroker läuft im Docker auf QNAP. Dort im Terminal führt "iobroker state get 192.168.123.45" zu folgendem:

<img width="519" alt="Bildschirmfoto 2021-09-04 um 10 27 52" src="https://user-images.githubusercontent.com/38688960/132088755-7e1d324a-9235-4748-b6ad-69c1b775c685.png">

Leider kenne ich mich nicht sehr gut aus.

**Comment by sbormann** [comment]
Und was passiert, wenn Du die automatische Übersetzung ausschaltest?

**Comment by hardl1** [comment]
Dann  wird es in der Form "12.345 kWh" angezeigt. 

Ich habe es nur als Fehler empfunden, da in der Übersetzung manche Zahlen mit "12.345 kWh" und andere mit "12,345 kWh" angezeigt werden, obwohl sie nur geringfügig abweichen.

**Comment by sbormann** [comment]
Ok, aber dann gehört es denke ich wirklich zum Übersetzer Deines Browsers und nicht zu ioBroker/Alias-Manager. Viel Erfolg beim Klären! VG!
