### ISSUE TITLE
Free datapoints in alias structure

### ISSUE THREAD

**Issue by ALomonosov** [sbormann/ioBroker.alias-manager#22]
I propose to realize the possibility of creating a free working datapoints in the alias structure without establishing a connection with the target datapoint. This will give the opportunity to create in the same structure not only links to real devices, but also parameters that change the logic of their work.
For example, for a lamp such a parameter can be shown, it is turned on by a motion sensor or switch.

**Comment by sbormann** [comment]
Hi, I'm not sure if I completely understand what you mean. Could you please provide a more detailed example?

**Comment by ALomonosov** [comment]
I think, objects for convenient use need parameters (options).
I think the most convenient structure is like this (example):
Lamps.FirstFloor.Lamp1 {this is an alias}
- Lamps.FirstFloor.Lamp1.State {this is datapoint, linked to the real device. Present in the Alias-manager}
- Lamps. FirstFloor.Lamp1.ManualOn {this datapoint is parameter (option) to the alias. Not linked to the real device and can be set by script or another adapter. Absent in the Alias-manager. In this example indicate is state was changed by motion detector or by switch}
Lamps.FirstFloor.Lamp {next alias}
...
This structure allows to conveniently run objects through the script, and work with them from the adapters (SmartControl, for example).
Possible use for:
1. The light is turn on by motion detector or by switch. If by motion detector, lamp turns off through the time interval, if by switch, lamp turns off only with the switch.
2. Turning off sockets and light when arming. Part of the sockets / lamps should not be turned off (refrigerator, parking). Turned off sockets should be returned to the previous state when disarming.
And so on…

Sorry my English ☹

**Comment by sbormann** [comment]
Hi,
This is a very good and interesting idea. But:
Alias-Manager only creates the alias-datapoints. They are managed by ioBroker directly. Unfortunatly you can create such a datapoint (without an alias link target) by the alias-manager, but iobroker does not allow to write values to such da datapoint.
Therefore you need to create an issue with your feature-request at iobroker/js-controller. 
Please keep me informed!
Best regards!

**Comment by Videonisse** [comment]
I like this idea as well. 

As I understand it, currently you must create a "dummy" DP in the "0_userdata" space to store this state. The disadvantage is that you then have an extra place from where your data for the Alias must be maintained. 

Would be great if a better solution could be implemented.

**Comment by ALomonosov** [comment]
It is very sad...
Another variant: Enter the "User datapoint" type and synchronize it with mirror datapoint in the branch "0_userdata"?
Automatically create, modify and delete datapoint in the "0_userdata" branch when performing these actions with "User datapoint".
Of course, there will be duplication of datapoints, but it will be a convenient structure without increasing user's labor costs and maintaining the concept of ioBroker.
Issue on JS -Controller I will do. I think it need to ask for ability to create (using by adapter tools) in the adapter branch datapoints, accessible to the external editing.

**Comment by ALomonosov** [comment]
Hi!
I checked several adapters and saw that they had the ability to change the value of datapoints in the adapter branch.
For example, time-switch, smartcontrol, mpd ...
So, ioBroker has a way to create datapoints in the adapter's branch that can be changed from outside?

**Comment by sbormann** [comment]
Yes, but not in the alias.0 branch (here it seems to be forbidden)

**Comment by ALomonosov** [comment]
I created issue at iobroker/js-controller/
[https://github.com/ioBroker/ioBroker.js-controller/issues/1592](url)

**Comment by sbormann** [comment]
I think this is stale, therefore i close this for now. Please reopen, if any further help is needed.
