### ISSUE TITLE
Feature Request: Deselect or Select ALL Datapoints

### ISSUE THREAD

**Issue by daes10** [sbormann/ioBroker.alias-manager#23]
When I click on "Automatic Datapoints" :
![grafik](https://user-images.githubusercontent.com/44786122/146638400-11d10907-3105-4471-bd43-fd89292caf89.png)

I get a lot of Datapoint like in my case with WLED.

Is or can be there a feature where to disable or enable ALL Datapoint at all? Because when i want to select only a few, i must manually deselect all selected Datapoints, every time.

![grafik](https://user-images.githubusercontent.com/44786122/146638436-f81af3ba-e257-45f4-93f0-de17b6627d34.png)
Here on the left side. It would be nice if the button is on the right of the button "Delete Datapoint-List".

**Comment by sbormann** [comment]
Hi, has been added to the latest github-version. Please install it via the cat-logo in admin and test it.

**Comment by wuliwux** [comment]
Hi, i have test it in my install with hue lamps and it works great!

greets

**Comment by sbormann** [comment]
👍
