### ISSUE TITLE
Dark Theme. Button colors are low contrast

### ISSUE THREAD

**Issue by GermanBluefox** [sbormann/ioBroker.alias-manager#27]
**Describe the bug**  
Regular buttons on the Dark theme are low contrasted. There are too similar colors and it is not visible.

**To Reproduce**  
Admin driver 5.2.3 (stable)
1. Set the dark theme for admin'
2. Install Alias adapter
3. Click on the 'Alias-Manager' point in the side panel (a similar problem with Alias Manager)
4. Navigate to 'Manage Aliases'

The button 'New Alias' is low contrasted
[https://i.imgur.com/8afRmqJ.png](https://i.imgur.com/8afRmqJ.png)

![image](https://user-images.githubusercontent.com/4582016/153187360-f2f5b3c7-87d0-4bc0-a51b-7b873dad22c0.png)

**Expected behavior**  
The button should be more contrasted

**Versions:**  
 - Adapter version: 5.2.3 stable
 - JS-Controller version: 3.3.22
 - Node version: 14.18.1
 - Operating system: Raspbian 11

**Additional context**

**Comment by sbormann** [comment]
Fixed with 1.2.5. Thanks for reporting.
