### ISSUE TITLE
common.states deleted on save

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.alias-manager#35]
**Describe the bug**  
I got some alias with common.states (List of text values for numbers like {0:'aus',1:'an',2:'auto'}) and if I save a change with the manager, common.states were deleted. 

**To Reproduce**  
1. Create a alias
2. Add common.states
3. Open with adapter
4. Edit and save it
5. common.states is deleted

**Expected behavior**  
Maybe to edit common.states over this adapter

**Comment by sbormann** [comment]
Unbelievable, that this was not recognized before. Fix is on github. Thanks
