### ISSUE TITLE
Pulsieren zur Aufforderung des Speicherns von Änderungen deaktivieren

### ISSUE THREAD

**Issue by systemofapwne** [sbormann/ioBroker.alias-manager#39]
**Describe the bug**  
Aktuell pulsiert der "Alle Änderungen Speichern" Button, sobald eine Änderung gemacht wurde. 
Dies ist recht ablenkend und sollte auf eine weniger visuell invasive Art geändert werden. Z.B. ein Farbwechsel des Buttons.

**To Reproduce**  
1. Einen Alias hinzufügen oder editieren
2. "Alle Änderungen Speichern" button pulsiert nun

**Comment by sbormann** [comment]
Hi, 
danke für die Anregung. Das ganze ist sicher Geschmackssache - aber so vergisst man wenigstens nicht zu speichern. Mir gefällt das deshalb ganz gut so. Aktuell fehlt mir auch leider einfach die Zeit das zu ändern, ich behalte es aber mal im Hinterkopf.
LG
