### ISSUE TITLE
Support of Separate linked Write and Read targets

### ISSUE THREAD

**Issue by Videonisse** [sbormann/ioBroker.alias-manager#5]
Many thanks for developing this GUI!

Since js.controller 3.x, an Alias can have separate targets for write and read objects. This is currently not implemented in any GUI and must be created manually using Admin in the Raw settings for the Alias object.

It would be very nice if it also was supported by the Alias Manager.

Reference - Alias Documentation (in German, it's missing in the English version): https://www.iobroker.net/#de/documentation/dev/aliases.md

Example from manually created Alias with separate Targets:
`{
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1616591695319,
  "common": {
    "name": "currentstate",
    "role": "state",
    "type": "boolean",
    "desc": "Manually created",
    "read": true,
    "write": true,
    "def": false,
    "alias": {
      "id": {
          "read": "knx.0.VVS_och_VA.Ventilation.Köksfläkt_Status_Värde",
          "write": "knx.0.VVS_och_VA.Ventilation.Köksfläkt_Värde"
      },
      "read": "val > 40",
      "write": "val ? 80 : 40"
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "alias.0.uuid-533453-334345.fan.currentstate",
  "type": "state"
}`

**Comment by sbormann** [comment]
Solved with 0.1.0
